;; (ad-activate 'magit-status)
;; (ad-activate 'magit-log)
;; (ad-disable-advice 'magit-log 'around 'magit-fullscreen)
;; (ad-disable-advice 'magit-status 'around 'magit-fullscreen)
(setq with-editor-emacsclient-executable "emacsclient")
;; (setq magit-ediff-dwim-show-on-hunks t)
;;(setq vc-follow-symlinks)
