(global-set-key (kbd "C-S-b") 'projectile-compile-project)
(global-set-key (kbd "C-S-t") 'projectile-test-project)
(global-set-key (kbd "C-S-t") 'projectile-test-project)
(global-set-key (kbd "C-c p p") 'projectile-switch-project)
(global-set-key (kbd "C-c p f") 'projectile-find-file)
